/**
 * Loads reference data from its authentic sources.
 *
 *   npm run db:seed                     GeoNames + World Bank → the configured project
 *   npm run db:seed -- --only=indicators  refresh World Bank indicators only
 *   npm run db:seed -- --limit=5000       top-N cities only (staging / demos)
 *   npm run db:seed -- --dry-run          download + parse + report, write nothing
 *   npm run db:seed:sql                 regenerate the committed dev fixture
 *                                       supabase/seed.sql (top 300 cities)
 *   --refresh                           re-download GeoNames files
 *
 * Writes use SUPABASE_SECRET_KEY and are idempotent upserts, so re-running
 * refreshes data in place. Cities that disappear from GeoNames are NOT deleted
 * (that would cascade into caches and analytics); remove them deliberately.
 */

import { writeFileSync } from "node:fs";
import {
  ensureGeoNamesFiles,
  GEONAMES_ATTRIBUTION,
  loadGeoNames,
  type AliasRow,
  type CityRow,
  type CountryRow,
  type GeoNamesDataset,
} from "./sources/geonames";
import {
  loadWorldBankIndicators,
  WORLD_BANK_ATTRIBUTION,
  type IndicatorRow,
} from "./sources/world-bank";

const args = process.argv.slice(2);
const flag = (name: string) => args.includes(`--${name}`);
const option = (name: string) =>
  args.find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3) ?? null;

const emitSqlPath = option("emit-sql");
const only = option("only"); // "geonames" | "indicators" | null
const dryRun = flag("dry-run");
const limitArg = option("limit");
const limit = limitArg !== null ? Number.parseInt(limitArg, 10) : emitSqlPath ? 300 : null;

if (limit !== null && (!Number.isInteger(limit) || limit <= 0)) {
  console.error("--limit must be a positive integer");
  process.exit(1);
}
if (only !== null && only !== "geonames" && only !== "indicators") {
  console.error("--only must be 'geonames' or 'indicators'");
  process.exit(1);
}

const log = (message: string) => console.log(`  · ${message}`);

function subset(data: GeoNamesDataset): GeoNamesDataset {
  if (limit === null) return data;
  const cities = data.cities.slice(0, limit);
  const ids = new Set(cities.map((c) => c.id));
  return { ...data, cities, aliases: data.aliases.filter((a) => ids.has(a.city_id)) };
}

// ---------------------------------------------------------------------------
// SQL emission (supabase/seed.sql)
// ---------------------------------------------------------------------------

function lit(value: string | number | null | Record<string, string>): string {
  if (value === null) return "null";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "null";
  if (typeof value === "object") return `${lit(JSON.stringify(value))}::jsonb`;
  return `'${value.replace(/'/g, "''")}'`;
}

function insertSql(table: string, columns: string[], rows: unknown[][], conflict: string): string {
  if (rows.length === 0) return "";
  const chunks: string[] = [];
  for (let i = 0; i < rows.length; i += 500) {
    const values = rows
      .slice(i, i + 500)
      .map((row) => `  (${row.map((v) => lit(v as never)).join(", ")})`)
      .join(",\n");
    chunks.push(
      `insert into public.${table} (${columns.join(", ")}) values\n${values}\n${conflict};\n`
    );
  }
  return chunks.join("\n");
}

function renderSeed(
  geo: GeoNamesDataset,
  indicators: IndicatorRow[],
  wbUpdated: string | null
): string {
  const header = `-- =============================================================================
-- Development seed — GENERATED by \`npm run db:seed:sql\`; do not edit by hand.
--
-- Loaded automatically by \`supabase db reset\` (local stack only; hosted
-- projects are seeded with \`npm run db:seed\`). Contents:
--   * all ${geo.countries.length} countries and the ${geo.cities.length} most populous cities (+ search aliases)
--     from ${GEONAMES_ATTRIBUTION}
--   * country-level indicators from ${WORLD_BANK_ATTRIBUTION}${wbUpdated ? ` (WDI last updated ${wbUpdated})` : ""}
-- Generated ${new Date().toISOString().slice(0, 10)}.
-- =============================================================================
`;
  return [
    header,
    insertSql(
      "countries",
      ["iso2", "iso3", "name", "continent", "capital", "population"],
      geo.countries.map((c) => [c.iso2, c.iso3, c.name, c.continent, c.capital, c.population]),
      "on conflict (iso2) do nothing"
    ),
    insertSql(
      "cities",
      [
        "id",
        "city",
        "city_ascii",
        "slug",
        "lat",
        "lng",
        "country",
        "iso2",
        "iso3",
        "admin_name",
        "capital",
        "population",
      ],
      geo.cities.map((c) => [
        c.id,
        c.city,
        c.city_ascii,
        c.slug,
        c.lat,
        c.lng,
        c.country,
        c.iso2,
        c.iso3,
        c.admin_name,
        c.capital,
        c.population,
      ]),
      "on conflict (id) do nothing"
    ),
    insertSql(
      "city_aliases",
      ["city_id", "alias"],
      geo.aliases.map((a) => [a.city_id, a.alias]),
      "on conflict do nothing"
    ),
    insertSql(
      "country_indicators",
      [
        "iso2",
        "price_level_index",
        "price_level_year",
        "homicide_rate_per_100k",
        "homicide_year",
        "physicians_per_1000",
        "physicians_year",
        "source",
      ],
      indicators.map((r) => [
        r.iso2,
        r.price_level_index,
        r.price_level_year,
        r.homicide_rate_per_100k,
        r.homicide_year,
        r.physicians_per_1000,
        r.physicians_year,
        r.source,
      ]),
      "on conflict (iso2) do nothing"
    ),
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Upserts through the Data API (secret key)
// ---------------------------------------------------------------------------

async function upsertAll(geo: GeoNamesDataset | null, indicators: IndicatorRow[] | null) {
  const { secretClient, describeTarget } = await import("./env");
  const db = secretClient();
  console.log(`\nWriting to ${describeTarget()}`);

  async function batched<T>(
    label: string,
    rows: T[],
    size: number,
    write: (chunk: T[]) => Promise<void>
  ) {
    for (let i = 0; i < rows.length; i += size) {
      await write(rows.slice(i, i + size));
      process.stdout.write(`\r  · ${label}: ${Math.min(i + size, rows.length)}/${rows.length}`);
    }
    if (rows.length > 0) process.stdout.write("\n");
  }

  if (geo) {
    await batched<CountryRow>("countries", geo.countries, 500, async (chunk) => {
      const { error } = await db.from("countries").upsert(chunk, { onConflict: "iso2" });
      if (error) throw new Error(`countries: ${error.message}`);
    });
    await batched<CityRow>("cities", geo.cities, 1000, async (chunk) => {
      const { error } = await db.from("cities").upsert(chunk, { onConflict: "id" });
      if (error) throw new Error(`cities: ${error.message}`);
    });
    // Replace aliases per batch of cities so removed alternate names disappear.
    const aliasesByCity = new Map<number, AliasRow[]>();
    for (const alias of geo.aliases) {
      const list = aliasesByCity.get(alias.city_id) ?? [];
      list.push(alias);
      aliasesByCity.set(alias.city_id, list);
    }
    await batched<CityRow>("aliases (by city)", geo.cities, 500, async (chunk) => {
      const ids = chunk.map((c) => c.id);
      const { error: deleteError } = await db.from("city_aliases").delete().in("city_id", ids);
      if (deleteError) throw new Error(`city_aliases delete: ${deleteError.message}`);
      const rows = ids.flatMap((id) => aliasesByCity.get(id) ?? []);
      if (rows.length === 0) return;
      const { error } = await db.from("city_aliases").insert(rows);
      if (error) throw new Error(`city_aliases insert: ${error.message}`);
    });
  }

  if (indicators) {
    await batched<IndicatorRow>("country indicators", indicators, 500, async (chunk) => {
      const { error } = await db.from("country_indicators").upsert(
        chunk.map((row) => ({ ...row, imported_at: new Date().toISOString() })),
        {
          onConflict: "iso2",
        }
      );
      if (error) throw new Error(`country_indicators: ${error.message}`);
    });
  }
}

// ---------------------------------------------------------------------------

async function main() {
  console.log("Reference data");
  await ensureGeoNamesFiles({ refresh: flag("refresh"), log });

  const full = loadGeoNames();
  log(
    `GeoNames: ${full.countries.length} countries, ${full.cities.length} cities, ${full.aliases.length} aliases` +
      ` (skipped ${full.skipped.invalidRows} invalid, ${full.skipped.unknownCountry} unknown-country rows)`
  );
  const geo = subset(full);
  if (limit !== null) log(`limited to the ${geo.cities.length} most populous cities`);

  let indicators: IndicatorRow[] | null = null;
  let wbUpdated: string | null = null;
  if (only !== "geonames") {
    const iso3ToIso2 = new Map(full.countries.map((c) => [c.iso3, c.iso2]));
    const result = await loadWorldBankIndicators(iso3ToIso2, log);
    indicators = result.rows;
    wbUpdated = result.lastUpdated;
    log(
      `World Bank: indicators for ${indicators.length} countries (WDI updated ${wbUpdated ?? "n/a"})`
    );
  }

  if (emitSqlPath) {
    writeFileSync(emitSqlPath, renderSeed(geo, indicators ?? [], wbUpdated));
    console.log(`\n✓ wrote ${emitSqlPath}`);
    return;
  }
  if (dryRun) {
    console.log("\n✓ dry run — nothing written");
    return;
  }

  await upsertAll(only === "indicators" ? null : geo, indicators);
  console.log("\n✓ reference data loaded");
}

main().catch((error) => {
  console.error(`\n✗ ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
});
