services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: bestcityspots:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
